{
 "title": "Loki Minimal Logs Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "LokiDS", "label": "Loki Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Error Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |= \"ERROR\" |~ \"Container: (app1|app4)\"\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (\r\n  count_over_time({job=\"dummy-app\"}[$__range])\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |= \"ERROR\" |~ \"Container: (app1|app4)\"\r\n"
    }
   ]
  },
  {
   "title": "All Stdout Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=~\".+\"}"
    }
   ]
  },
  {
   "title": "App1, App4, App5 Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |~ \"Container: (app1|app4|app5)\"\r\n\r\n"
    }
   ]
  }
 ]
}